// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cargomanagementsystem.DAL.DATA;

namespace cargomanagementsystem.DAL.Migrations
{
    [DbContext(typeof(cargomanagementDbcontext))]
    [Migration("20220204163514_createcustomer")]
    partial class createcustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cargomanagementsystem.Entity.Model.Customerdetails", b =>
                {
                    b.Property<int>("custId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("custAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("custCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("custPhone")
                        .HasColumnType("int");

                    b.Property<string>("custname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("custpincode")
                        .HasColumnType("int");

                    b.Property<string>("recAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recID")
                        .HasColumnType("int");

                    b.Property<string>("recNmae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recPhone")
                        .HasColumnType("int");

                    b.Property<int>("recpincode")
                        .HasColumnType("int");

                    b.Property<string>("rectCity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("custId");

                    b.ToTable("customer_details");
                });

            modelBuilder.Entity("cargomanagementsystem.Entity.Model.cargomanagementRegister", b =>
                {
                    b.Property<string>("CustEmailid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Confirmpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mobile")
                        .HasColumnType("int");

                    b.HasKey("CustEmailid");

                    b.ToTable("Register");
                });
#pragma warning restore 612, 618
        }
    }
}
